version: "3.8"

services:
  backend_dev:
    build: ./backend
    container_name: backend_dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data/database.db:/app/app/database.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend_dev:
    build: ./frontend
    container_name: frontend_dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend_dev
    volumes:
      - ./frontend:/app
