services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./media:/app/images
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - BACKEND_APP_IMAGES_URL=http://192.168.0.95:8000/media
    depends_on:
      - backend
    networks:
      - dinivrey-net

networks:
  dinivrey-net:
    driver: bridge
