version: "3.8"

services:
  backend_prod:
    image: dockerhub_user/backend_prod:${VERSION}
    container_name: backend_prod
    restart: always
    ports:
      - "8001:8000"

  frontend_prod:
    image: dockerhub_user/frontend_prod:${VERSION}
    container_name: frontend_prod
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend_prod
