name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # срабатывает только на пуш в main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

    # 4. Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
