name: Publish Docker Images to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract PR number as version
        run: |
          MSG="$(git log -1 --pretty=%B)"
          if [[ "$MSG" =~ Merge\ pull\ request\ \#([0-9]+) ]]; then
            echo "VERSION=1.0.${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "VERSION=1.0.0" >> $GITHUB_ENV
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push Backend
        run: |
          USERNAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${USERNAME}/dinivrey-backend:${VERSION}
          docker build -t $IMAGE_NAME ./backend
          docker push $IMAGE_NAME

      - name: Build & Push Frontend
        run: |
          USERNAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${USERNAME}/dinivrey-frontend:${VERSION}
          docker build -t $IMAGE_NAME ./frontend
          docker push $IMAGE_NAME
